services:
  db:
    image: postgres:18
    container_name: rio_tinto_db
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: rio_tinto
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rio_tinto
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
