export {
  handleAcceptRequest,
  handleGetAllFriendsBookings,
  handleGetFriendBookings,
  handleGetMyProfile,
  handleIncomingRequests,
  handleListFriends,
  handleOutgoingRequests,
  handleRejectRequest,
  handleRemoveFriend,
  handleSearchUsers,
  handleSendRequest,
  handleUpdatePrivacy,
  handleUpdateUsername,
} from "./routes.js";
